"""Continue the Task 007 stage-2 replay through in-place decode rounds.

Starts at the stage-2 entry and follows the natural GetLocalTime scan.
It does not patch a branch, force a flag, or start at the found path.
Generated bytes are written only when --work-dir is set.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import math
import sys
from pathlib import Path

import pefile
from capstone import CS_ARCH_X86, CS_MODE_32, Cs
from unicorn import (
    Uc,
    UC_ARCH_X86,
    UC_HOOK_CODE,
    UC_HOOK_MEM_INVALID,
    UC_HOOK_MEM_READ,
    UC_HOOK_MEM_WRITE,
    UC_MODE_32,
)
from unicorn.x86_const import (
    UC_X86_REG_EAX,
    UC_X86_REG_EBP,
    UC_X86_REG_EBX,
    UC_X86_REG_ECX,
    UC_X86_REG_EDI,
    UC_X86_REG_EDX,
    UC_X86_REG_EIP,
    UC_X86_REG_ESI,
    UC_X86_REG_ESP,
)

IMAGE = 0x400000
K32_BASE = 0x76240000
GETLOCALTIME_RVA = 0x1D430
STACK = 0x00200000
STACK_SIZE = 0x00100000
BLOCK_RVA = 0x819000
DECRYPT_RVA = 0x81CB21
DECRYPT_LEN = 0x7000
ENTRY_RVA = 0x81C6C5
FOUND_RVA = 0x81CCC6
ROUND1_PRODUCER = 0x81CE47
ROUND1_DONE = 0x81CE77
ROUND1_LO = 0x81CEB5
ROUND1_LEN = 0x71CC
ROUND2_LO = 0x81D633
ROUND2_HI = 0x824093
TAIL_A = (0x002CE000, 0x007EA000)
TAIL_B = (0x00819000, 0x00912000)
ZTL = (0x005FC19F, 0x005FC1B0, 0x005FC1C1)
SLOTS = (0x0081A621, 0x0081B45D)
AES_KEY = bytes.fromhex(
    "130000000800000006000000B40000001B0000000F0000003300000052000000"
)
IV_PREFIX = bytes.fromhex("EC3F77A445D071BFB79820FC4BE9B3E1")
IV_SEED = bytes.fromhex("F25350C6")
TEXT_ANCHORS = ("List.wz", ".wz", "WS2_32", "WSAStartup", "connect", "send", "recv")


def sha256(blob: bytes) -> str:
    return hashlib.sha256(blob).hexdigest()


def entropy(blob: bytes) -> float:
    if not blob:
        return 0.0
    counts = [0] * 256
    for byte in blob:
        counts[byte] += 1
    total = len(blob)
    value = 0.0
    for count in counts:
        if not count:
            continue
        prob = count / total
        value -= prob * math.log2(prob)
    return value


def instruction_density(blob: bytes) -> float:
    if not blob:
        return 0.0
    md = Cs(CS_ARCH_X86, CS_MODE_32)
    sample = blob[: min(len(blob), 0x2000)]
    covered = sum(insn.size for insn in md.disasm(sample, 0))
    return covered / len(sample)


def map_pe(uc: Uc, path: Path, base: int) -> int:
    pe = pefile.PE(str(path), fast_load=True)
    size = (int(pe.OPTIONAL_HEADER.SizeOfImage) + 0xFFF) & ~0xFFF
    blob = path.read_bytes()
    uc.mem_map(base, size)
    uc.mem_write(base, blob[: int(pe.OPTIONAL_HEADER.SizeOfHeaders)])
    for section in pe.sections:
        raw = blob[section.PointerToRawData : section.PointerToRawData + section.SizeOfRawData]
        if raw:
            uc.mem_write(base + section.VirtualAddress, raw)
    return size


def export_layout(path: Path) -> dict:
    pe = pefile.PE(str(path), fast_load=True)
    pe.parse_data_directories(directories=[pefile.DIRECTORY_ENTRY["IMAGE_DIRECTORY_ENTRY_EXPORT"]])
    directory = pe.OPTIONAL_HEADER.DATA_DIRECTORY[0]
    exp = pe.DIRECTORY_ENTRY_EXPORT
    symbols = {}
    for symbol in exp.symbols:
        if symbol.name and symbol.address:
            symbols[symbol.name.decode("ascii", "replace")] = symbol.address
    return {
        "export_rva": directory.VirtualAddress,
        "export_size": directory.Size,
        "functions_rva": exp.struct.AddressOfFunctions,
        "names_rva": exp.struct.AddressOfNames,
        "ordinals_rva": exp.struct.AddressOfNameOrdinals,
        "n_functions": exp.struct.NumberOfFunctions,
        "n_names": exp.struct.NumberOfNames,
        "symbols": symbols,
    }


def region_of(rva: int) -> str:
    if TAIL_A[0] <= rva < TAIL_A[1]:
        return "tail-A"
    if TAIL_B[0] <= rva < TAIL_B[1]:
        return "tail-B"
    if 0 <= rva < 0x9DA000:
        return "maple-image"
    return "outside-image"


def direct_targets(blob: bytes, rva: int, limit: int = 400) -> list[tuple[int, str, int]]:
    md = Cs(CS_ARCH_X86, CS_MODE_32)
    found = []
    for insn in md.disasm(blob, rva):
        if insn.mnemonic in ("call", "jmp") or (insn.mnemonic.startswith("j") and insn.mnemonic != "jmp"):
            if insn.op_str.startswith("0x"):
                found.append((insn.address, insn.mnemonic, int(insn.op_str, 16)))
        if len(found) >= limit:
            break
    return found


def aligned_pointers(blob: bytes, rva: int) -> list[tuple[int, int]]:
    found = []
    for offset in range(0, len(blob) - 3, 4):
        value = int.from_bytes(blob[offset : offset + 4], "little")
        if K32_BASE <= value < K32_BASE + 0x200000 or IMAGE <= value < IMAGE + 0x9DA000:
            found.append((rva + offset, value))
    return found


def anchor_hits(blob: bytes, rva: int) -> list[dict]:
    hits = []
    for name, needle in (
        ("aes-key", AES_KEY),
        ("iv-prefix", IV_PREFIX),
        ("iv-seed", IV_SEED),
        ("rtti-av", b".?AV"),
        ("rtti-au", b".?AU"),
    ):
        start = 0
        while True:
            index = blob.find(needle, start)
            if index < 0 or len(hits) > 40:
                break
            hits.append({"anchor_type": name, "rva": rva + index, "evidence": needle[:8].hex()})
            start = index + 1
    for text in TEXT_ANCHORS:
        for encoding, label in (("ascii", text), ("utf-16le", text + "-utf16")):
            needle = text.encode(encoding)
            index = blob.find(needle)
            if index >= 0:
                hits.append({"anchor_type": label, "rva": rva + index, "evidence": text})
    hits.append(
        {
            "anchor_type": "msvc-prologue-count",
            "rva": rva,
            "evidence": str(blob.count(bytes.fromhex("558bec"))),
        }
    )
    return hits


def skip_seh(uc: Uc, address: int, seh_head: list[int], state: dict) -> bool:
    raw = bytes(uc.mem_read(address, 8))
    if raw[0] != 0x64:
        return False
    kind = None
    disp = None
    if raw[1:3] == b"\xff\x35":
        kind, disp = "push", int.from_bytes(raw[3:7], "little")
    elif raw[1:3] == b"\x89\x25":
        kind, disp = "store", int.from_bytes(raw[3:7], "little")
    elif raw[1:3] == b"\x8f\x05":
        kind, disp = "pop", int.from_bytes(raw[3:7], "little")
    if kind is None or disp != 0:
        state["why"] = "fs-beyond-seh-head"
        state["eip"] = address
        state["bytes"] = raw.hex()
        uc.emu_stop()
        return True
    esp = uc.reg_read(UC_X86_REG_ESP)
    if kind == "push":
        esp -= 4
        uc.mem_write(esp, (seh_head[0] & 0xFFFFFFFF).to_bytes(4, "little"))
        uc.reg_write(UC_X86_REG_ESP, esp)
    elif kind == "store":
        seh_head[0] = esp
    else:
        seh_head[0] = int.from_bytes(uc.mem_read(esp, 4), "little")
        uc.reg_write(UC_X86_REG_ESP, esp + 4)
    uc.reg_write(UC_X86_REG_EIP, address + 7)
    return True


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--exe", type=Path, required=True)
    parser.add_argument("--kernel32", type=Path, default=Path(r"C:\Windows\SysWOW64\kernel32.dll"))
    parser.add_argument("--block", type=Path, required=True)
    parser.add_argument("--work-dir", type=Path)
    parser.add_argument("--json-out", type=Path)
    parser.add_argument("--safety-cap", type=int, default=6_000_000)
    args = parser.parse_args(argv)

    client_hash = sha256(args.exe.read_bytes())
    kernel_hash = sha256(args.kernel32.read_bytes())
    block = bytearray(args.block.read_bytes())
    block_hash = sha256(bytes(block[0x14:]))
    exports = export_layout(args.kernel32)
    getlocal = exports["symbols"].get("GetLocalTime")
    if getlocal != GETLOCALTIME_RVA:
        raise SystemExit(f"GetLocalTime RVA is {getlocal}, expected {GETLOCALTIME_RVA:#x}")

    uc = Uc(UC_ARCH_X86, UC_MODE_32)
    image_size = map_pe(uc, args.exe, IMAGE)
    k32_size = map_pe(uc, args.kernel32, K32_BASE)
    uc.mem_map(STACK, STACK_SIZE)
    off = DECRYPT_RVA - BLOCK_RVA
    for index in range(DECRYPT_LEN):
        block[off + index] = (block[off + index] + 1) & 0xFF
    uc.mem_write(IMAGE + BLOCK_RVA, bytes(block))
    uc.mem_write(IMAGE + 0x81802B, (K32_BASE + GETLOCALTIME_RVA).to_bytes(4, "little"))
    uc.reg_write(UC_X86_REG_ESP, STACK + STACK_SIZE - 0x100)
    uc.reg_write(UC_X86_REG_EBP, 0)

    export_vas = {
        "directory": K32_BASE + exports["export_rva"],
        "functions": K32_BASE + exports["functions_rva"],
        "names": K32_BASE + exports["names_rva"],
        "ordinals": K32_BASE + exports["ordinals_rva"],
    }
    export_span = (K32_BASE + exports["export_rva"], K32_BASE + exports["export_rva"] + exports["export_size"])

    seh_head = [0xFFFFFFFF]
    state: dict = {
        "count": 0,
        "why": "safety-cap",
        "scan_hits": [],
        "found_at": None,
        "rounds": [],
        "events": [],
        "slot_reads": [],
        "k32_reads": [],
        "ztl_writes": [],
        "cross_writes": [],
        "phase": "to-found",
        "round2_edge": None,
        "round2_hits": 0,
        "round2_writers": {},
        "last_write_insn": 0,
        "open_round": None,
        "executed_pages": set(),
        "anchors_seen": [],
    }

    def event(kind: str, **fields) -> None:
        fields["event_type"] = kind
        fields["instruction_count"] = state["count"]
        fields["eip"] = uc.reg_read(UC_X86_REG_EIP)
        state["events"].append(fields)
        if kind in ("E1", "E2", "E3", "E4", "E10") and state["why"] == "safety-cap":
            state["why"] = kind
            uc.emu_stop()

    def snapshot(rva: int, length: int) -> bytes:
        return bytes(uc.mem_read(IMAGE + rva, length))

    def close_explicit(round_id: str, producer: int, rva: int, length: int, pre: bytes, extra: dict) -> None:
        post = snapshot(rva, length)
        pre_targets = {(item[1], item[2]) for item in direct_targets(pre, rva)}
        post_targets = direct_targets(post, rva)
        new_targets = [item for item in post_targets if (item[1], item[2]) not in pre_targets][:30]
        pre_ptrs = {item[1] for item in aligned_pointers(pre, rva)}
        new_ptrs = [item for item in aligned_pointers(post, rva) if item[1] not in pre_ptrs][:30]
        row = {
            "round_id": round_id,
            "producer_rva": producer,
            "start_rva": rva,
            "end_rva": rva + length,
            "length": length,
            "pre_sha256": sha256(pre),
            "post_sha256": sha256(post),
            "entropy_before": round(entropy(pre), 4),
            "entropy_after": round(entropy(post), 4),
            "density_before": round(instruction_density(pre), 4),
            "density_after": round(instruction_density(post), 4),
            "new_control_targets": [f"{item[1]}:{item[2]:08X}" for item in new_targets],
            "new_absolute": [f"{item[0]:08X}->{item[1]:08X}" for item in new_ptrs],
            "anchors": anchor_hits(post, rva),
            **extra,
        }
        state["rounds"].append(row)
        for hit in row["anchors"]:
            key = (hit["anchor_type"], hit["rva"], hit["evidence"])
            if key not in {(item["anchor_type"], item["rva"], item["evidence"]) for item in state["anchors_seen"]}:
                hit["round_id"] = round_id
                hit["region_start"] = rva
                hit["region_end"] = rva + length
                state["anchors_seen"].append(hit)

    deny = {
        "IsDebuggerPresent",
        "CheckRemoteDebuggerPresent",
        "NtQueryInformationProcess",
        "ZwQueryInformationProcess",
        "NtQuerySystemInformation",
        "OutputDebugStringA",
        "OutputDebugStringW",
        "NtSetInformationThread",
    }
    modules: dict[int, dict] = {}
    by_name: dict[str, int] = {}
    va_name: dict[int, str] = {}

    def remember_module(base: int, path: Path, label: str) -> None:
        if base in modules:
            return
        info = export_layout(path)
        modules[base] = {"path": str(path), "label": label, "exports": info["symbols"]}
        by_name[label.lower()] = base
        by_name[Path(label).stem.lower()] = base
        for name, rva in info["symbols"].items():
            va_name[base + rva] = name

    def read_cstr(address: int) -> str:
        return bytes(uc.mem_read(address, 260)).split(b"\x00", 1)[0].decode("ascii", "replace")

    def dword_at(address: int) -> int:
        return int.from_bytes(uc.mem_read(address, 4), "little")

    def stdcall_return(nargs: int, value: int) -> None:
        esp = uc.reg_read(UC_X86_REG_ESP)
        ret = dword_at(esp)
        if state["resolved"]:
            state["resolved"][-1]["return_rva"] = hex(ret - IMAGE)
        uc.reg_write(UC_X86_REG_EAX, value & 0xFFFFFFFF)
        uc.reg_write(UC_X86_REG_ESP, esp + 4 + 4 * nargs)
        uc.reg_write(UC_X86_REG_EIP, ret)

    def ensure_mapped(path: Path, base: int) -> None:
        try:
            map_pe(uc, path, base)
        except Exception:
            return

    layout_rows = []
    layout_path = Path("result/process-layout-snapshot.csv")
    if layout_path.exists():
        with layout_path.open(encoding="utf-8", newline="") as handle:
            layout_rows = list(csv.DictReader(handle))
    remember_module(K32_BASE, args.kernel32, "kernel32.dll")
    state["resolved"] = []
    state["arena"] = 0x20000000

    def lookup_module(text: str) -> tuple[int, Path] | None:
        key = text.lower().replace("/", "\\")
        base_name = Path(key).name
        stem = Path(base_name).stem
        for row in layout_rows:
            if row["module_name"].lower() in (base_name, stem, base_name + ".dll"):
                path = Path(row["normalized_path"].strip('"').replace("%USERPROFILE%", str(Path.home())))
                return int(row["module_base"], 16), path
        if stem in by_name:
            return by_name[stem], args.kernel32
        return None

    def stub_loadlibrary() -> None:
        esp = uc.reg_read(UC_X86_REG_ESP)
        arg = dword_at(esp + 4)
        name = read_cstr(arg)
        found = lookup_module(name)
        state["resolved"].append({"api": "LoadLibraryA", "name": name, "found": bool(found)})
        if not found or not found[1].exists():
            state["why"] = "E10"
            state["missing_module"] = name
            uc.emu_stop()
            return
        base, path = found
        ensure_mapped(path, base)
        remember_module(base, path, Path(name).name)
        stdcall_return(1, base)

    def stub_getprocaddress() -> None:
        esp = uc.reg_read(UC_X86_REG_ESP)
        module = dword_at(esp + 4)
        name_ptr = dword_at(esp + 8)
        info = modules.get(module)
        if info is None or name_ptr < 0x10000:
            state["why"] = "E10"
            state["missing_module"] = hex(module)
            uc.emu_stop()
            return
        name = read_cstr(name_ptr)
        rva = info["exports"].get(name)
        if not rva:
            state["why"] = "E10"
            state["missing_module"] = f"{info['label']}!{name}"
            uc.emu_stop()
            return
        va = module + rva
        state["resolved"].append({"api": "GetProcAddress", "name": f"{info['label']}!{name}", "va": hex(va)})
        stdcall_return(2, va)

    def stub_virtualalloc() -> None:
        esp = uc.reg_read(UC_X86_REG_ESP)
        requested = dword_at(esp + 4)
        size = max(dword_at(esp + 8), 0x1000)
        size = (size + 0xFFF) & ~0xFFF
        base = requested or state["arena"]
        base &= ~0xFFF
        if not requested:
            state["arena"] = base + size
        try:
            uc.mem_map(base, size)
        except Exception:
            pass
        state["resolved"].append({"api": "VirtualAlloc", "name": hex(base), "va": hex(size)})
        event("E8", detail=f"VirtualAlloc {base:#x} size {size:#x}")
        stdcall_return(4, base)

    def stub_virtualprotect() -> None:
        stdcall_return(4, 1)

    def stub_virtualfree() -> None:
        stdcall_return(3, 1)

    def stub_getlocaltime() -> None:
        esp = uc.reg_read(UC_X86_REG_ESP)
        dest = dword_at(esp + 4)
        # Fixed SYSTEMTIME. Not read from the host clock and not a debugger flag.
        uc.mem_write(dest, bytes.fromhex("da07010000001f000000000000000000"))
        state["resolved"].append({"api": "GetLocalTime", "name": "2010-01-31", "va": hex(dest)})
        stdcall_return(1, 0)

    stubs = {
        K32_BASE + exports["symbols"]["LoadLibraryA"]: stub_loadlibrary,
        K32_BASE + exports["symbols"]["GetProcAddress"]: stub_getprocaddress,
    }
    for api_name, handler in (
        ("VirtualAlloc", stub_virtualalloc),
        ("VirtualProtect", stub_virtualprotect),
        ("VirtualFree", stub_virtualfree),
        ("GetLocalTime", stub_getlocaltime),
    ):
        if api_name in exports["symbols"]:
            stubs[K32_BASE + exports["symbols"][api_name]] = handler

    def on_code(_uc, address, _size, _user):
        if skip_seh(uc, address, seh_head, state):
            return
        if address in stubs:
            stubs[address]()
            return
        state["count"] += 1
        state["executed_pages"].add(address & ~0xFFF)
        rva = address - IMAGE if IMAGE <= address < IMAGE + image_size else None
        if rva == 0x81CC65 and len(state["scan_hits"]) < 8:
            state["scan_hits"].append(uc.reg_read(UC_X86_REG_ESI))
        if rva == FOUND_RVA and state["found_at"] is None:
            state["found_at"] = {
                "insn": state["count"],
                "eax": uc.reg_read(UC_X86_REG_EAX),
                "esi": uc.reg_read(UC_X86_REG_ESI),
                "edi": uc.reg_read(UC_X86_REG_EDI),
                "ecx": uc.reg_read(UC_X86_REG_ECX),
                "edx": uc.reg_read(UC_X86_REG_EDX),
            }
            state["round1_pre"] = snapshot(ROUND1_LO, ROUND1_LEN)
            state["phase"] = "round1"
        if state["found_at"] and rva is None and not (K32_BASE <= address < K32_BASE + k32_size):
            event("E4", detail=f"eip {address:#x} outside Tail B")
            return
        if state["found_at"] and rva is not None and not (TAIL_B[0] <= rva < TAIL_B[1]):
            event("E4", detail=f"eip rva {rva:#x} outside Tail B")
            return
        if state["found_at"] and K32_BASE <= address < K32_BASE + k32_size:
            called = va_name.get(address, hex(address))
            if called in deny:
                state["missing_module"] = called
                event("E10", detail=f"debugger-sensitive API {called} was not answered")
                return
            state["missing_module"] = called
            esp = uc.reg_read(UC_X86_REG_ESP)
            arg_text = ""
            try:
                arg_text = read_cstr(dword_at(esp + 4))
            except Exception:
                arg_text = ""
            if called == "CreateFileA":
                ret = dword_at(esp)
                args7 = [dword_at(esp + 4 * (index + 1)) for index in range(7)]
                window = b""
                region = b""
                region_rva = None
                if IMAGE <= ret < IMAGE + image_size:
                    window = bytes(uc.mem_read(ret - 16, 160))
                    lo = min(ret, args7[0]) - 0x80
                    lo = max(lo, IMAGE)
                    size = min(0x1000, max(ret, args7[0]) + 0x500 - lo)
                    region = bytes(uc.mem_read(lo, size))
                    region_rva = lo - IMAGE
                state["probe"] = {
                    "eip": uc.reg_read(UC_X86_REG_EIP),
                    "esp": esp,
                    "return": ret,
                    "args": args7,
                    "arg_text": arg_text,
                    "eax": uc.reg_read(UC_X86_REG_EAX),
                    "window_rva": (ret - 16 - IMAGE) if window else None,
                    "window": window.hex(),
                    "region_rva": region_rva,
                    "region": region.hex(),
                    "insn": state["count"],
                }
            event("E10", detail=f"no stub for {called} arg={arg_text[:120]!r}")
            return
        if rva == ROUND1_PRODUCER and state.get("round1_sample") is None and state["phase"] == "round1":
            ebx = uc.reg_read(UC_X86_REG_EBX)
            edx = uc.reg_read(UC_X86_REG_EDX)
            state["round1_sample"] = {"ebx": ebx, "edx": edx, "dest": (edx + ebx) & 0xFFFFFFFF}
        if rva == ROUND1_DONE and state["phase"] == "round1":
            sample = state.get("round1_sample") or {}
            close_explicit(
                "1",
                ROUND1_PRODUCER,
                ROUND1_LO,
                ROUND1_LEN,
                state["round1_pre"],
                {
                    "iteration_count": ROUND1_LEN // 4,
                    "word_size": 4,
                    "direction": "backward",
                    "transform": "xor/add/xor in place",
                    "sample": {key: hex(value) for key, value in sample.items()},
                },
            )
            state["round2_pre"] = snapshot(ROUND2_LO, ROUND2_HI - ROUND2_LO)
            head = snapshot(0x81D58D, 5)
            back = snapshot(0x81D622, 5)
            state["round2_edge"] = (
                {"at": 0x81D622, "size": 5, "target": 0x81D594, "mnemonic": "jmp"}
                if head == bytes.fromhex("bb991a0000") and back == bytes.fromhex("e96dffffff")
                else None
            )
            state["phase"] = "round2"
        if state["phase"] == "round2" and rva == 0x81D594:
            state["round2_hits"] += 1
            if state["round2_hits"] == 1:
                eax = uc.reg_read(UC_X86_REG_EAX)
                state["round2_regs"] = {
                    "eax": eax,
                    "ebx": uc.reg_read(UC_X86_REG_EBX),
                    "edx": uc.reg_read(UC_X86_REG_EDX),
                    "sample_in": dword_at(eax) if eax else 0,
                }
        if state["phase"] == "round2" and state["round2_edge"] and state["round2_hits"] and rva == 0x81D633:
            regs = state.get("round2_regs") or {}
            writers = state["round2_writers"]
            producer = max(writers, key=writers.get) if writers else state["round2_edge"]["target"]
            close_explicit(
                "2",
                producer,
                ROUND2_LO,
                ROUND2_HI - ROUND2_LO,
                state["round2_pre"],
                {
                    "iteration_count": state["round2_hits"],
                    "word_size": 4,
                    "direction": "backward",
                    "transform": "in-place dword loop",
                    "edge": {key: (hex(value) if isinstance(value, int) else value) for key, value in state["round2_edge"].items()},
                    "regs": {key: hex(value) for key, value in regs.items()},
                },
            )
            state["phase"] = "explore"
            state["explore_start"] = state["count"]
        if state["phase"] == "explore":
            idle = state["count"] - max(state["last_write_insn"], state["explore_start"])
            if idle > 250_000 and state["why"] == "safety-cap":
                state["why"] = "idle-after-rounds"
                state["eip"] = address
                uc.emu_stop()
                return
        if state["count"] > args.safety_cap:
            state["why"] = "safety-cap"
            state["eip"] = address
            uc.emu_stop()

    def note_image_write(address: int, size: int) -> None:
        rva = address - IMAGE
        eip = uc.reg_read(UC_X86_REG_EIP)
        producer = eip - IMAGE if IMAGE <= eip < IMAGE + image_size else eip
        state["last_write_insn"] = state["count"]
        for slot in ZTL:
            if slot <= address - IMAGE < slot + 16 or rva <= slot < rva + size:
                blob = bytes(uc.mem_read(address, size))
                state["ztl_writes"].append({"slot": hex(slot), "producer": hex(producer), "bytes": blob.hex(), "size": size})
                event("E3", detail=f"ztl {slot:#x} from {producer:#x}")
                return
        if not (TAIL_B[0] <= rva < TAIL_B[1]):
            state["cross_writes"].append(
                {"producer": hex(producer), "dest": hex(rva), "size": size, "region": region_of(rva)}
            )
            kind = "E2" if region_of(rva) == "tail-A" else "E1"
            event(kind, detail=f"write {size} bytes at {rva:#x} from {producer:#x} ({region_of(rva)})")

    def on_write(_uc, _access, address, size, _value, _user):
        page = address & ~0xFFF
        if page in state["executed_pages"]:
            try:
                uc.ctl_remove_cache(page, page + 0x1000)
            except Exception:
                pass
        if not state["found_at"]:
            return
        if STACK <= address < STACK + STACK_SIZE:
            return
        if IMAGE <= address < IMAGE + image_size:
            producer = uc.reg_read(UC_X86_REG_EIP) - IMAGE
            if state["phase"] == "round2" and TAIL_B[0] <= address - IMAGE < TAIL_B[1]:
                state["round2_writers"][producer] = state["round2_writers"].get(producer, 0) + 1
            if size == 4:
                value = int.from_bytes(uc.mem_read(address, 4), "little")
                owner = next((base for base in modules if base <= value < base + 0x400000), None)
                if owner is not None and len(state["resolved"]) < 80:
                    state["events"].append(
                        {
                            "event_type": "E7",
                            "instruction_count": state["count"],
                            "eip": uc.reg_read(UC_X86_REG_EIP),
                            "detail": f"stored {value:#x} ({va_name.get(value, 'module-pointer')}) at {(address - IMAGE):#x}",
                        }
                    )
            note_image_write(address, size)
            return
        if not (K32_BASE <= address < K32_BASE + k32_size):
            event("E8", detail=f"write {size} bytes at {address:#x}")

    def on_read(_uc, _access, address, size, _value, _user):
        if not state["found_at"]:
            return
        for slot in SLOTS:
            va = IMAGE + slot
            if va <= address < va + 4 or address <= va < address + size:
                if len(state["slot_reads"]) < 12:
                    state["slot_reads"].append(
                        {
                            "insn": state["count"],
                            "eip": uc.reg_read(UC_X86_REG_EIP),
                            "slot": hex(slot),
                            "address": hex(address),
                            "size": size,
                            "eax": uc.reg_read(UC_X86_REG_EAX),
                            "ebx": uc.reg_read(UC_X86_REG_EBX),
                            "ecx": uc.reg_read(UC_X86_REG_ECX),
                            "edx": uc.reg_read(UC_X86_REG_EDX),
                            "esi": uc.reg_read(UC_X86_REG_ESI),
                            "edi": uc.reg_read(UC_X86_REG_EDI),
                        }
                    )
                event_seen = any(item.get("event_type") == "E5" for item in state["events"])
                if not event_seen:
                    event("E5", detail=f"read slot {slot:#x}")
                    state["why_keep"] = state["why"]
                    state["why"] = state["why_keep"]
        if K32_BASE <= address < K32_BASE + k32_size and len(state["k32_reads"]) < 80 and state["slot_reads"]:
            kind = "kernel32"
            for name, va in export_vas.items():
                if name == "directory":
                    continue
                if va <= address < va + 4 * max(exports["n_names"], 1):
                    kind = name
            if export_span[0] <= address < export_span[1]:
                kind = "export-directory" if kind == "kernel32" else kind
            state["k32_reads"].append(
                {
                    "insn": state["count"],
                    "eip": hex(uc.reg_read(UC_X86_REG_EIP)),
                    "address": hex(address),
                    "size": size,
                    "kind": kind,
                }
            )
            if kind != "kernel32" and not any(item.get("event_type") == "E6" for item in state["events"]):
                state["events"].append(
                    {
                        "event_type": "E6",
                        "instruction_count": state["count"],
                        "eip": uc.reg_read(UC_X86_REG_EIP),
                        "detail": f"{kind} at {address:#x}",
                    }
                )

    def on_invalid(_uc, access, address, size, _value, _user):
        state["why"] = "E10"
        state["fault"] = {
            "access": int(access),
            "address": address,
            "size": size,
            "eip": uc.reg_read(UC_X86_REG_EIP),
        }
        state["events"].append(
            {
                "event_type": "E10",
                "instruction_count": state["count"],
                "eip": state["fault"]["eip"],
                "detail": f"unmapped access {int(access)} at {address:#x} size {size}",
            }
        )
        uc.emu_stop()
        return False

    uc.hook_add(UC_HOOK_CODE, on_code)
    uc.hook_add(UC_HOOK_MEM_WRITE, on_write)
    uc.hook_add(UC_HOOK_MEM_READ, on_read)
    uc.hook_add(UC_HOOK_MEM_INVALID, on_invalid)
    try:
        uc.emu_start(IMAGE + ENTRY_RVA, 0xFFFFFFFF, count=args.safety_cap)
    except Exception as exc:  # unicorn raises when a hook stops the run
        state["error"] = str(exc)
        if state["why"] == "safety-cap":
            state["why"] = f"error:{exc.__class__.__name__}"
    state["final_eip"] = uc.reg_read(UC_X86_REG_EIP)
    state["ztl"] = {hex(rva): bytes(uc.mem_read(IMAGE + rva, 16)).hex() for rva in ZTL}
    state["slots"] = {hex(rva): bytes(uc.mem_read(IMAGE + rva, 4)).hex() for rva in SLOTS}
    tail_a = bytes(uc.mem_read(IMAGE + TAIL_A[0], 0x1000))
    state["tail_a_nonzero"] = any(tail_a)

    if args.work_dir and state.get("probe"):
        args.work_dir.mkdir(parents=True, exist_ok=True)
        (args.work_dir / "probe-window.bin").write_bytes(bytes(uc.mem_read(IMAGE + 0x856000, 0xC000)))
    if args.work_dir and state.get("rounds"):
        args.work_dir.mkdir(parents=True, exist_ok=True)
        # Keep only hashes in the JSON; the slices stay in the work directory.
        for row in state["rounds"]:
            name = f"round-{row['round_id']}-post.bin"
            start = row["start_rva"]
            length = row["end_rva"] - start
            (args.work_dir / name).write_bytes(bytes(uc.mem_read(IMAGE + start, length)))

    summary = {
        "client_sha256": client_hash,
        "kernel32_sha256": kernel_hash,
        "kernel32_base": hex(K32_BASE),
        "kernel32_size": hex(k32_size),
        "getlocaltime_rva": hex(GETLOCALTIME_RVA),
        "getlocaltime_va": hex(K32_BASE + GETLOCALTIME_RVA),
        "t2_block_sha256": block_hash,
        "export": {key: hex(value) if isinstance(value, int) else value for key, value in exports.items() if key != "symbols"},
        "found_at": state["found_at"],
        "scan_hits": [hex(item) for item in state["scan_hits"]],
        "why": state["why"],
        "instructions": state["count"],
        "final_eip": hex(state["final_eip"]),
        "phase": state["phase"],
        "rounds": state["rounds"],
        "events": state["events"][:80],
        "slot_reads": state["slot_reads"],
        "k32_reads": state["k32_reads"],
        "cross_writes": state["cross_writes"][:20],
        "ztl_writes": state["ztl_writes"],
        "ztl": state["ztl"],
        "slots": state["slots"],
        "tail_a_nonzero": state["tail_a_nonzero"],
        "fault": state.get("fault"),
        "error": state.get("error"),
        "anchors": state["anchors_seen"],
        "resolved": state.get("resolved", []),
        "missing_module": state.get("missing_module"),
        "probe": state.get("probe"),
        "round2_hits": state.get("round2_hits"),
        "image_size": hex(image_size),
    }
    text = json.dumps(summary, indent=2)
    if args.json_out:
        args.json_out.parent.mkdir(parents=True, exist_ok=True)
        args.json_out.write_text(text, encoding="utf-8")
    brief = {
        "why": summary["why"],
        "found_at": summary["found_at"],
        "scan_hits": summary["scan_hits"],
        "phase": summary["phase"],
        "instructions": summary["instructions"],
        "rounds": [
            {
                "id": row["round_id"],
                "producer": hex(row["producer_rva"]),
                "range": f"{row['start_rva']:#x}-{row['end_rva']:#x}",
                "count": row.get("iteration_count"),
                "pre": row["pre_sha256"][:16],
                "post": row["post_sha256"][:16],
            }
            for row in summary["rounds"]
        ],
        "events": [item.get("event_type") for item in summary["events"][:20]],
        "slot_reads": len(summary["slot_reads"]),
        "k32_reads": summary["k32_reads"][:8],
        "tail_a": summary["tail_a_nonzero"],
        "resolved": summary["resolved"][:12],
        "missing": summary["missing_module"],
        "round2_hits": summary["round2_hits"],
        "ztl": summary["ztl"],
        "fault": summary["fault"],
    }
    print(json.dumps(brief, indent=2))
    replay_ok = (
        state["found_at"] is not None
        and state["scan_hits"][:2] == [0x76250000, 0x76240000]
        and state["found_at"]["esi"] == K32_BASE
    )
    return 0 if replay_ok else 2


if __name__ == "__main__":
    sys.exit(main())
