"""Bounded offline emulation of the MapleStory entry loader.

Maps the PE at its ImageBase, zero-fills virtual tails, and stops when execution
leaves the image. It does not patch branches and does not answer debugger queries.
Generated bytes are not written unless --work-dir is set, and that directory is
meant to stay out of git.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import sys
from pathlib import Path

import pefile
from unicorn import (
    Uc,
    UC_ARCH_X86,
    UC_HOOK_CODE,
    UC_HOOK_MEM_INVALID,
    UC_HOOK_MEM_READ,
    UC_HOOK_MEM_WRITE,
    UC_MODE_32,
)
from unicorn.x86_const import (
    UC_X86_REG_EAX,
    UC_X86_REG_EBP,
    UC_X86_REG_EBX,
    UC_X86_REG_ECX,
    UC_X86_REG_EDI,
    UC_X86_REG_EDX,
    UC_X86_REG_EIP,
    UC_X86_REG_ESI,
    UC_X86_REG_ESP,
)

TAIL_A = (0x002CE000, 0x007EA000)
TAIL_B = (0x00819000, 0x00912000)
WATCH = (
    0x005FC19F,
    0x005FC1B0,
    0x005FC1C1,
    0x00862E76,
    0x00862FB0,
    0x00819014,
)
AES_KEY = bytes.fromhex(
    "130000000800000006000000B40000001B0000000F0000003300000052000000"
)
IV_PREFIX = bytes.fromhex("EC3F77A445D071BFB79820FC4BE9B3E1")
IV_SEED = bytes.fromhex("F25350C6")


def entropy(blob: bytes) -> float:
    if not blob:
        return 0.0
    counts = [0] * 256
    for byte in blob:
        counts[byte] += 1
    total = len(blob)
    value = 0.0
    for count in counts:
        if count:
            prob = count / total
            value -= prob * math.log2(prob)
    return value


def instruction_density(blob: bytes) -> float:
    from capstone import CS_ARCH_X86, CS_MODE_32, Cs

    if not blob:
        return 0.0
    md = Cs(CS_ARCH_X86, CS_MODE_32)
    covered = 0
    for insn in md.disasm(blob[: min(len(blob), 0x2000)], 0):
        covered += insn.size
    sample = min(len(blob), 0x2000)
    return covered / sample


def find_bytes(blob: bytes, needle: bytes, base_rva: int) -> list[int]:
    hits = []
    start = 0
    while True:
        index = blob.find(needle, start)
        if index < 0:
            return hits
        hits.append(base_rva + index)
        start = index + 1


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Offline entry-loader emulation")
    parser.add_argument("exe")
    parser.add_argument("--budget", type=int, default=8_000_000)
    parser.add_argument("--work-dir")
    parser.add_argument("--json-out")
    parser.add_argument(
        "--seh-slot",
        action="store_true",
        help="Map a TEB page whose only defined slot is fs:[0] = end of the SEH chain",
    )
    args = parser.parse_args(argv)

    pe = pefile.PE(args.exe, fast_load=True)
    image = int(pe.OPTIONAL_HEADER.ImageBase)
    entry = image + int(pe.OPTIONAL_HEADER.AddressOfEntryPoint)
    size = int(pe.OPTIONAL_HEADER.SizeOfImage)
    blob = Path(args.exe).read_bytes()

    stack_base = 0x00200000
    stack_size = 0x00100000
    uc = Uc(UC_ARCH_X86, UC_MODE_32)
    uc.mem_map(image, size)
    uc.mem_map(stack_base, stack_size)
    # fs:[0] only. A real FS base cannot be set on this Unicorn build, and a
    # zero-filled TEB would make a later PEB read look like "no debugger".
    seh_head = [0xFFFFFFFF]
    headers = int(pe.OPTIONAL_HEADER.SizeOfHeaders)
    uc.mem_write(image, blob[:headers])
    for section in pe.sections:
        raw = blob[section.PointerToRawData : section.PointerToRawData + section.SizeOfRawData]
        if raw:
            uc.mem_write(image + section.VirtualAddress, raw)

    writes: list[tuple[int, int]] = []
    first_tail_a = None
    first_tail_b = None
    executed_tail = None
    executed_watch = {rva: False for rva in WATCH}
    max_source_read = 0x912259
    stop_reason = {"why": "budget", "eip": None, "fault": None, "insn": 0}
    state = {"count": 0, "recent": []}

    def on_write(uc_vm, _access, address, size_written, _value, _user):
        nonlocal first_tail_a, first_tail_b
        if not (image <= address < image + size):
            return
        rva = address - image
        writes.append((rva, size_written))
        if first_tail_a is None and TAIL_A[0] <= rva < TAIL_A[1]:
            first_tail_a = {"rva": rva, "size": size_written, "insn": state["count"]}
        if first_tail_b is None and TAIL_B[0] <= rva < TAIL_B[1]:
            first_tail_b = {"rva": rva, "size": size_written, "insn": state["count"]}

    def skip_seh_head(uc_vm, address: int) -> bool:
        if not args.seh_slot:
            return False
        raw = bytes(uc_vm.mem_read(address, 8))
        if raw[0] != 0x64:
            return False
        kind = None
        disp = None
        length = 7
        if raw[1:3] == b"\xff\x35":
            kind = "push"
            disp = int.from_bytes(raw[3:7], "little")
        elif raw[1:3] == b"\x89\x25":
            kind = "store"
            disp = int.from_bytes(raw[3:7], "little")
        elif raw[1:3] == b"\x8f\x05":
            kind = "pop"
            disp = int.from_bytes(raw[3:7], "little")
        if kind is None or disp != 0:
            stop_reason["why"] = "fs-beyond-seh-head"
            stop_reason["eip"] = address
            stop_reason["bytes"] = raw.hex()
            uc_vm.emu_stop()
            return True
        esp = uc_vm.reg_read(UC_X86_REG_ESP)
        if kind == "push":
            esp -= 4
            uc_vm.mem_write(esp, (seh_head[0] & 0xFFFFFFFF).to_bytes(4, "little"))
            uc_vm.reg_write(UC_X86_REG_ESP, esp)
        elif kind == "store":
            seh_head[0] = esp
        else:
            seh_head[0] = int.from_bytes(uc_vm.mem_read(esp, 4), "little")
            uc_vm.reg_write(UC_X86_REG_ESP, esp + 4)
        state["fs0"] = state.get("fs0", 0) + 1
        uc_vm.reg_write(UC_X86_REG_EIP, address + length)
        return True

    def on_code(uc_vm, address, _size, _user):
        nonlocal executed_tail
        if skip_seh_head(uc_vm, address):
            return
        recent = state["recent"]
        recent.append(address)
        if len(recent) > 12:
            del recent[0]
        state["count"] += 1
        if state["count"] > args.budget:
            stop_reason["why"] = "budget"
            stop_reason["eip"] = address
            uc_vm.emu_stop()
            return
        if address < image or address >= image + size:
            stop_reason["why"] = "left-image"
            stop_reason["eip"] = address
            uc_vm.emu_stop()
            return
        rva = address - image
        if executed_tail is None and TAIL_B[0] <= rva < TAIL_B[1]:
            executed_tail = {"rva": rva, "insn": state["count"]}
        if rva in executed_watch:
            executed_watch[rva] = True

    def on_read(uc_vm, _access, address, size_read, _value, _user):
        nonlocal max_source_read
        if image + 0x912259 <= address < image + 0x9D8000:
            max_source_read = max(max_source_read, address - image + size_read)
        return None

    def on_invalid(uc_vm, access, address, size_bad, _value, _user):
        stop_reason["why"] = "unmapped"
        stop_reason["fault"] = address
        stop_reason["access"] = int(access)
        stop_reason["fault_size"] = size_bad
        try:
            stop_reason["eip"] = uc_vm.reg_read(UC_X86_REG_EIP)
        except Exception:
            stop_reason["eip"] = None
        uc_vm.emu_stop()
        return False

    uc.hook_add(UC_HOOK_MEM_WRITE, on_write)
    uc.hook_add(UC_HOOK_MEM_READ, on_read)
    uc.hook_add(UC_HOOK_CODE, on_code)
    uc.hook_add(UC_HOOK_MEM_INVALID, on_invalid)
    uc.reg_write(UC_X86_REG_ESP, stack_base + stack_size - 0x1000)
    uc.reg_write(UC_X86_REG_EBP, 0)
    for reg in (UC_X86_REG_EAX, UC_X86_REG_EBX, UC_X86_REG_ECX, UC_X86_REG_EDX, UC_X86_REG_ESI, UC_X86_REG_EDI):
        uc.reg_write(reg, 0)

    try:
        uc.emu_start(entry, 0, count=args.budget)
        if stop_reason["eip"] is None:
            stop_reason["why"] = "emu-return"
            stop_reason["eip"] = uc.reg_read(UC_X86_REG_EIP)
    except Exception as exc:  # unicorn raises UcError when a hook stops the run
        stop_reason["detail"] = str(exc)
        if stop_reason["why"] == "budget":
            stop_reason["why"] = f"error:{exc.__class__.__name__}"
        if stop_reason.get("eip") is None:
            try:
                stop_reason["eip"] = uc.reg_read(UC_X86_REG_EIP)
            except Exception:
                stop_reason["eip"] = None
    stop_reason["insn"] = state["count"]

    # Merge write intervals. Later writes can land below earlier ones.
    ranges: list[list[int]] = []
    for rva, size_written in sorted(writes, key=lambda item: item[0]):
        end = rva + size_written
        if ranges and rva <= ranges[-1][1]:
            ranges[-1][1] = max(ranges[-1][1], end)
            ranges[-1][2] += 1
        else:
            ranges.append([rva, end, 1])
    large = [
        {"start": start, "end": end, "writes": count, "length": end - start}
        for start, end, count in ranges
        if end - start >= 0x100
    ]
    small = [
        {"start": start, "end": end, "writes": count, "length": end - start}
        for start, end, count in ranges
        if end - start < 0x100
    ]

    def block_info(start_rva: int, end_rva: int) -> dict:
        data = bytes(uc.mem_read(image + start_rva, end_rva - start_rva))
        return {
            "start": start_rva,
            "end": end_rva,
            "length": end_rva - start_rva,
            "sha256": hashlib.sha256(data).hexdigest(),
            "entropy": round(entropy(data), 4),
            "instruction_density_2k": round(instruction_density(data), 4),
            "aes_key_rvas": find_bytes(data, AES_KEY, start_rva),
            "iv_prefix_rvas": find_bytes(data, IV_PREFIX, start_rva),
            "iv_seed_rvas": find_bytes(data, IV_SEED, start_rva),
            "ascii": {
                name: find_bytes(data, name.encode("ascii"), start_rva)[:8]
                for name in ("List.wz", ".wz", "WS2_32", "connect", "send", "recv")
            },
            "utf16": {
                name: find_bytes(data, name.encode("utf-16le"), start_rva)[:8]
                for name in ("List.wz", "WS2_32", "connect", "send", "recv")
            },
            "msvc_prologue_count": data.count(bytes.fromhex("558bec")),
        }

    watched = {}
    for rva in WATCH:
        watched[f"0x{rva:08X}"] = bytes(uc.mem_read(image + rva, 16)).hex()

    tail_b_nonzero_end = TAIL_B[0]
    page = bytes(uc.mem_read(image + TAIL_B[0], TAIL_B[1] - TAIL_B[0]))
    for index in range(len(page) - 1, -1, -1):
        if page[index] != 0:
            tail_b_nonzero_end = TAIL_B[0] + index + 1
            break
    tail_a_page = bytes(uc.mem_read(image + TAIL_A[0], min(0x1000, TAIL_A[1] - TAIL_A[0])))

    summary = {
        "instructions": state["count"],
        "stop": stop_reason,
        "eip": None if stop_reason.get("eip") is None else int(stop_reason["eip"]),
        "first_write_tail_a": first_tail_a,
        "first_write_tail_b": first_tail_b,
        "first_execute_tail_b": executed_tail,
        "large_write_ranges": large[:40],
        "small_write_ranges": small[:20],
        "write_range_count": len(ranges),
        "tail_b_nonzero_end": tail_b_nonzero_end,
        "tail_a_first_page_nonzero": any(tail_a_page),
        "watched_16": watched,
        "watched_executed": {f"0x{rva:08X}": hit for rva, hit in executed_watch.items()},
        "packed_source_read_end": max_source_read,
        "fs0_ops": state.get("fs0", 0),
        "recent_eip": state["recent"],
        "eax": uc.reg_read(UC_X86_REG_EAX),
        "esp": uc.reg_read(UC_X86_REG_ESP),
        "tail_b_block": None
        if tail_b_nonzero_end <= TAIL_B[0]
        else block_info(TAIL_B[0], tail_b_nonzero_end),
    }
    text = json.dumps(summary, indent=2)
    if args.json_out:
        Path(args.json_out).write_text(text, encoding="utf-8")
    print(text)
    if args.work_dir and summary["tail_b_block"]:
        work = Path(args.work_dir)
        work.mkdir(parents=True, exist_ok=True)
        data = bytes(uc.mem_read(image + TAIL_B[0], tail_b_nonzero_end - TAIL_B[0]))
        (work / "tail-b-nonzero.bin").write_bytes(data)
    return 0


if __name__ == "__main__":
    sys.exit(main())
